apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-planner
  template:
    metadata:
      labels:
        app: trip-planner
    spec:
      containers:
        - image: mrwhoop/trip-planner:2024-01-14-20-05-53
          name: trip-planner
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              #value: jdbc:postgresql://cornelius.db.elephantsql.com:5432/wckrnamu
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: pg-conn
                  key: connection
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              #value: wckrnamu
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: pg-user
                  key: user
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              #value: v8LBJZpjvIG11HSJTs8XwJg8N9Okr04C
              valueFrom: #use Kubernetes secret for storing the password
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 60
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 60
            periodSeconds: 120

---

apiVersion: v1
kind: Service
metadata:
  name: trip-planner
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: trip-planner
